version: '3'
services:
  app:
    container_name: docker-file-server
    restart: always
    build: .
    ports:
      - '${SERVER_PORT}:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - './data-mongo:/data/db'
    ports:
      - '${DB_PORT}:27017'
